import React from 'react';
import './AiInsights.css';

const AiInsights = () => {
  return (
    <div className="insights-card">
      <div className="insights-header">
        <div>
          <h3>AI Insights</h3>
          <p>Generated by IntelliWatch AI</p>
        </div>
        <div className="updated-badge">Updated 2m ago</div>
      </div>
      
      <div className="insights-content">
        <p>There is a strong correlation between <strong>HubSpot's</strong> recent pricing changes and increased churn in the SMB segment. Consider targeting this segment with a custom campaign highlighting your transparent pricing model.</p>
      </div>
    </div>
  );
};

export default AiInsights;
